import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const jobs = [
  // Full Stack Engineers
  {
    title: 'Full Stack Engineer',
    company: 'Stripe',
    location: 'San Francisco, CA',
    locationType: 'HYBRID',
    jobType: 'Full Stack Engineer',
    experienceLevel: 'senior',
    salaryMin: 180000,
    salaryMax: 240000,
    description: `Stripe is looking for a Full Stack Engineer to join our payments infrastructure team. You'll work on building and scaling systems that process billions of dollars in transactions every year.\n\nYou'll collaborate closely with product managers and designers to ship features that matter to our merchants and their customers. Our stack includes React, TypeScript, Ruby, and Go.`,
    requirements: `• 5+ years of software engineering experience\n• Strong proficiency in TypeScript/JavaScript and React\n• Experience with server-side languages (Ruby, Go, or Python)\n• Understanding of distributed systems and scalability\n• Experience with SQL and NoSQL databases\n• Strong communication and collaboration skills`,
    applyUrl: 'https://stripe.com/jobs',
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Senior Full Stack Engineer',
    company: 'Figma',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Full Stack Engineer',
    experienceLevel: 'senior',
    salaryMin: 190000,
    salaryMax: 260000,
    description: `Join Figma's engineering team and help build the future of design collaboration. You'll work on features that are used by millions of designers worldwide.\n\nWe use React, TypeScript, WebAssembly, and C++ to build our real-time collaborative design tool.`,
    requirements: `• 6+ years of full stack engineering experience\n• Expert-level React and TypeScript skills\n• Experience with WebSockets or real-time systems\n• Proficiency in Node.js or similar backend runtime\n• Experience with browser performance optimization\n• Passion for developer and user experience`,
    applyUrl: 'https://figma.com/careers',
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Full Stack Engineer',
    company: 'Linear',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Full Stack Engineer',
    experienceLevel: 'mid',
    salaryMin: 150000,
    salaryMax: 200000,
    description: `Linear is building the next generation of project management tools. We're looking for a Full Stack Engineer to help build features that make software teams more productive.\n\nOur stack: React, TypeScript, GraphQL, Node.js, PostgreSQL.`,
    requirements: `• 3+ years of full stack engineering experience\n• Proficiency in React, TypeScript, and GraphQL\n• Experience with Node.js and PostgreSQL\n• Keen eye for design and UX detail\n• Ability to work independently in a remote environment`,
    applyUrl: 'https://linear.app/careers',
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Junior Full Stack Developer',
    company: 'Vercel',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Full Stack Engineer',
    experienceLevel: 'entry',
    salaryMin: 90000,
    salaryMax: 130000,
    description: `Vercel is hiring a Junior Full Stack Developer to help build the platform powering the modern web. You'll work on developer tools and infrastructure that enable teams to deploy and scale Next.js applications.\n\nGreat opportunity to learn from world-class engineers.`,
    requirements: `• 1-2 years of experience with React and Node.js\n• Familiarity with TypeScript\n• Understanding of REST APIs\n• Enthusiasm for learning and growing\n• Good communication skills`,
    applyUrl: 'https://vercel.com/careers',
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Lead Full Stack Engineer',
    company: 'Notion',
    location: 'New York, NY',
    locationType: 'HYBRID',
    jobType: 'Full Stack Engineer',
    experienceLevel: 'lead',
    salaryMin: 220000,
    salaryMax: 300000,
    description: `Notion is looking for a Lead Full Stack Engineer to guide a team of engineers building our core editor and collaboration features. You'll set technical direction, mentor engineers, and ship high-impact features.\n\nNotiontech stack: React, TypeScript, Node.js, PostgreSQL.`,
    requirements: `• 8+ years of software engineering experience\n• 3+ years in a technical lead or staff engineer role\n• Expert in React and TypeScript\n• Experience designing distributed systems\n• Strong mentorship and communication skills\n• Track record of leading large engineering projects`,
    applyUrl: 'https://notion.so/careers',
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },

  // Backend Engineers
  {
    title: 'Senior Backend Engineer',
    company: 'Airbnb',
    location: 'San Francisco, CA',
    locationType: 'HYBRID',
    jobType: 'Backend Engineer',
    experienceLevel: 'senior',
    salaryMin: 200000,
    salaryMax: 270000,
    description: `Airbnb's infrastructure team is growing. We're looking for a Senior Backend Engineer to help build and scale the systems that connect 4 million hosts with 900 million guest arrivals.\n\nYou'll work on high-scale distributed systems, data pipelines, and APIs in Java, Python, and Go.`,
    requirements: `• 5+ years backend engineering experience\n• Strong knowledge of Java, Python, or Go\n• Experience with distributed systems at scale\n• Familiarity with Kafka, Spark, or similar data streaming\n• Understanding of microservices architecture\n• Experience with cloud platforms (AWS/GCP)`,
    applyUrl: 'https://careers.airbnb.com',
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Backend Engineer - Payments',
    company: 'Coinbase',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Backend Engineer',
    experienceLevel: 'mid',
    salaryMin: 160000,
    salaryMax: 210000,
    description: `Coinbase is building the financial infrastructure for the crypto economy. Join our payments team to work on systems that process billions in crypto transactions daily.\n\nStack: Go, Ruby on Rails, PostgreSQL, Kafka.`,
    requirements: `• 3+ years of backend engineering\n• Experience with Go or Ruby\n• Strong understanding of financial systems or payments\n• Knowledge of cryptographic principles is a plus\n• Experience with PostgreSQL and Kafka\n• Commitment to high reliability and security`,
    applyUrl: 'https://coinbase.com/careers',
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Backend Engineer',
    company: 'Plaid',
    location: 'New York, NY',
    locationType: 'HYBRID',
    jobType: 'Backend Engineer',
    experienceLevel: 'mid',
    salaryMin: 150000,
    salaryMax: 200000,
    description: `Plaid connects people's financial accounts to apps they love. We're hiring a Backend Engineer to build and maintain the financial data APIs used by thousands of fintech companies.\n\nOur backend stack: Go, Python, PostgreSQL, Redis.`,
    requirements: `• 3+ years building backend services\n• Strong Go or Python skills\n• Experience with REST or GraphQL API design\n• Familiarity with financial data or fintech APIs a plus\n• Experience with PostgreSQL and Redis\n• Security-minded approach to development`,
    applyUrl: 'https://plaid.com/careers',
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Staff Backend Engineer',
    company: 'Databricks',
    location: 'San Francisco, CA',
    locationType: 'ONSITE',
    jobType: 'Backend Engineer',
    experienceLevel: 'lead',
    salaryMin: 250000,
    salaryMax: 350000,
    description: `Databricks is the data + AI company. We're looking for a Staff Backend Engineer to help build the next generation of our unified analytics platform.\n\nYou'll influence technical direction across multiple teams and work on challenging distributed systems problems in Scala and Python.`,
    requirements: `• 10+ years of software engineering experience\n• Deep expertise in Scala, Java, or Python\n• Experience with distributed data processing (Spark, Flink)\n• Strong systems design and architectural skills\n• Experience mentoring and leading technical projects\n• Excellent written and verbal communication`,
    applyUrl: 'https://databricks.com/company/careers',
    postedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Entry Level Backend Developer',
    company: 'Brex',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Backend Engineer',
    experienceLevel: 'entry',
    salaryMin: 100000,
    salaryMax: 140000,
    description: `Brex is looking for an Entry Level Backend Developer to join our growing engineering team. You'll work on APIs and services that power Brex's corporate credit card and financial management platform.\n\nStack: Elixir, PostgreSQL, Kafka.`,
    requirements: `• 0-2 years of backend development experience\n• Knowledge of at least one backend language (Python, Ruby, Go, Elixir)\n• Understanding of databases and SQL\n• Eagerness to learn and grow quickly\n• Good problem-solving skills`,
    applyUrl: 'https://brex.com/careers',
    postedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },

  // Frontend Engineers
  {
    title: 'Senior Frontend Engineer',
    company: 'Vercel',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Frontend Engineer',
    experienceLevel: 'senior',
    salaryMin: 175000,
    salaryMax: 240000,
    description: `Vercel is the platform for the modern web. We're looking for a Senior Frontend Engineer to help build the dashboard and developer experience for millions of developers deploying with Vercel.\n\nOur frontend is built with Next.js, React, and TypeScript.`,
    requirements: `• 5+ years of frontend engineering\n• Expert-level React and TypeScript\n• Deep understanding of web performance\n• Experience with Next.js or similar frameworks\n• Eye for design and attention to UX detail\n• Experience with CSS, Tailwind, or CSS-in-JS`,
    applyUrl: 'https://vercel.com/careers',
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Frontend Engineer',
    company: 'Loom',
    location: 'San Francisco, CA',
    locationType: 'HYBRID',
    jobType: 'Frontend Engineer',
    experienceLevel: 'mid',
    salaryMin: 140000,
    salaryMax: 185000,
    description: `Loom is on a mission to make async video communication effortless. We're looking for a Frontend Engineer to help build our web and desktop recording and playback experience.\n\nStack: React, TypeScript, Electron, WebRTC.`,
    requirements: `• 3+ years of frontend development experience\n• Strong React and TypeScript skills\n• Experience with WebRTC or media APIs is a plus\n• Knowledge of browser APIs and performance optimization\n• Attention to detail and good design sense`,
    applyUrl: 'https://loom.com/jobs',
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Lead Frontend Engineer',
    company: 'Spotify',
    location: 'New York, NY',
    locationType: 'HYBRID',
    jobType: 'Frontend Engineer',
    experienceLevel: 'lead',
    salaryMin: 210000,
    salaryMax: 280000,
    description: `Spotify is looking for a Lead Frontend Engineer to help define the technical direction for our web player and creator tools. You'll manage a team of 5-7 engineers and work closely with design and product.\n\nTech: React, TypeScript, GraphQL.`,
    requirements: `• 8+ years of frontend engineering\n• 3+ years leading frontend teams\n• Expert knowledge of React ecosystem\n• Experience with GraphQL and Apollo\n• Strong leadership and communication skills\n• Passion for music and audio technology is a plus`,
    applyUrl: 'https://spotifyjobs.com',
    postedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Junior Frontend Developer',
    company: 'Webflow',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Frontend Engineer',
    experienceLevel: 'entry',
    salaryMin: 85000,
    salaryMax: 120000,
    description: `Webflow empowers designers to build professional websites without writing code. We're hiring a Junior Frontend Developer to help build our visual design tool interface.\n\nThis is a great opportunity to grow as an engineer and work on a product used by 3.5 million designers.`,
    requirements: `• 1+ year of experience with React\n• Understanding of HTML, CSS, and JavaScript\n• Enthusiasm for design and UX\n• Attention to detail\n• Strong learning mindset`,
    applyUrl: 'https://webflow.com/careers',
    postedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
  },

  // DevOps
  {
    title: 'Senior DevOps Engineer',
    company: 'HashiCorp',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'DevOps',
    experienceLevel: 'senior',
    salaryMin: 170000,
    salaryMax: 230000,
    description: `HashiCorp is building the infrastructure automation stack for cloud and hybrid environments. We're looking for a Senior DevOps Engineer to help build and maintain our cloud infrastructure using our own tools: Terraform, Vault, and Consul.\n\nYou'll work on CI/CD pipelines, cloud infrastructure, and reliability engineering.`,
    requirements: `• 5+ years in DevOps/infrastructure engineering\n• Strong knowledge of Terraform and infrastructure as code\n• Experience with AWS, GCP, or Azure\n• Kubernetes and container orchestration expertise\n• Experience with CI/CD systems (GitHub Actions, Jenkins)\n• Linux administration and scripting skills`,
    applyUrl: 'https://hashicorp.com/careers',
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'DevOps Engineer',
    company: 'Cloudflare',
    location: 'Austin, TX',
    locationType: 'HYBRID',
    jobType: 'DevOps',
    experienceLevel: 'mid',
    salaryMin: 140000,
    salaryMax: 190000,
    description: `Cloudflare is on a mission to help build a better Internet. We're hiring a DevOps Engineer to support our growing engineering teams by building robust CI/CD pipelines and improving developer velocity.\n\nYou'll work with Kubernetes, Rust, and a globally distributed infrastructure.`,
    requirements: `• 3+ years of DevOps or SRE experience\n• Experience with Kubernetes and Docker\n• Strong scripting skills (Bash, Python, Go)\n• Experience with monitoring tools (Datadog, Prometheus)\n• Understanding of networking fundamentals\n• Experience with GitHub Actions or GitLab CI`,
    applyUrl: 'https://cloudflare.com/careers',
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Lead Platform Engineer',
    company: 'Datadog',
    location: 'New York, NY',
    locationType: 'ONSITE',
    jobType: 'DevOps',
    experienceLevel: 'lead',
    salaryMin: 230000,
    salaryMax: 310000,
    description: `Datadog is the monitoring and analytics platform for cloud infrastructure. We need a Lead Platform Engineer to guide our internal developer platform team.\n\nYou'll architect solutions that improve developer productivity across 5,000 engineers.`,
    requirements: `• 8+ years of platform or infrastructure engineering\n• Experience leading technical teams\n• Deep Kubernetes expertise\n• Experience building internal developer platforms\n• Strong communication and stakeholder management\n• Experience with observability tooling`,
    applyUrl: 'https://datadoghq.com/careers',
    postedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'DevOps Engineer - Entry Level',
    company: 'PagerDuty',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'DevOps',
    experienceLevel: 'entry',
    salaryMin: 90000,
    salaryMax: 125000,
    description: `PagerDuty is looking for an entry-level DevOps Engineer eager to learn cloud infrastructure and operations. You'll support our reliability engineering team and gain hands-on experience with AWS, Kubernetes, and Terraform.`,
    requirements: `• Basic understanding of Linux systems\n• Familiarity with at least one scripting language\n• Interest in cloud infrastructure and automation\n• Strong problem-solving mindset\n• Good communication skills`,
    applyUrl: 'https://pagerduty.com/careers',
    postedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
  },

  // Data Scientists
  {
    title: 'Senior Data Scientist',
    company: 'Netflix',
    location: 'Los Gatos, CA',
    locationType: 'HYBRID',
    jobType: 'Data Scientist',
    experienceLevel: 'senior',
    salaryMin: 220000,
    salaryMax: 300000,
    description: `Netflix is looking for a Senior Data Scientist to improve our content recommendation algorithms that serve 300 million subscribers. You'll develop novel ML models to personalize the Netflix experience.\n\nPython, Spark, TensorFlow are our core tools.`,
    requirements: `• PhD or 5+ years in data science or ML\n• Expertise in Python (pandas, scikit-learn, PyTorch/TensorFlow)\n• Experience with recommender systems\n• Strong statistics and probability background\n• Experience with A/B testing and causal inference\n• Ability to communicate findings to non-technical stakeholders`,
    applyUrl: 'https://jobs.netflix.com',
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Machine Learning Engineer',
    company: 'OpenAI',
    location: 'San Francisco, CA',
    locationType: 'ONSITE',
    jobType: 'Data Scientist',
    experienceLevel: 'senior',
    salaryMin: 300000,
    salaryMax: 500000,
    description: `OpenAI is working to ensure that artificial general intelligence benefits all of humanity. We're hiring Machine Learning Engineers to help train and improve our large language models.\n\nYou'll work on scaling ML systems, improving training efficiency, and evaluating model capabilities.`,
    requirements: `• 5+ years of ML engineering experience\n• Deep knowledge of transformer architectures\n• Experience with distributed training at scale\n• Strong Python and PyTorch skills\n• Experience with CUDA and GPU optimization\n• Research experience or publications a strong plus`,
    applyUrl: 'https://openai.com/careers',
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Data Scientist',
    company: 'Lyft',
    location: 'San Francisco, CA',
    locationType: 'HYBRID',
    jobType: 'Data Scientist',
    experienceLevel: 'mid',
    salaryMin: 160000,
    salaryMax: 210000,
    description: `Lyft is looking for a Data Scientist to work on our pricing and demand forecasting models. You'll use machine learning to predict rider demand, optimize pricing, and improve driver utilization.\n\nWe use Python, R, Spark, and Airflow.`,
    requirements: `• 3+ years in data science or quantitative research\n• Strong Python and SQL skills\n• Experience with ML modeling and feature engineering\n• Familiarity with time series forecasting\n• Experience with Spark or similar big data tools\n• Strong communication and data visualization skills`,
    applyUrl: 'https://lyft.com/careers',
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Junior Data Analyst',
    company: 'HubSpot',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Data Scientist',
    experienceLevel: 'entry',
    salaryMin: 80000,
    salaryMax: 110000,
    description: `HubSpot is hiring a Junior Data Analyst to help analyze product usage data and provide insights to drive business decisions. You'll work with SQL, Python, and Looker to build dashboards and reports.\n\nGreat opportunity to grow into a data science role.`,
    requirements: `• 0-2 years of data analysis experience\n• Strong SQL skills\n• Familiarity with Python or R\n• Experience with data visualization tools\n• Analytical thinking and curiosity\n• Excellent communication skills`,
    applyUrl: 'https://hubspot.com/jobs',
    postedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
  },

  // Product Managers
  {
    title: 'Senior Product Manager',
    company: 'Slack',
    location: 'San Francisco, CA',
    locationType: 'HYBRID',
    jobType: 'Product Manager',
    experienceLevel: 'senior',
    salaryMin: 180000,
    salaryMax: 240000,
    description: `Slack is looking for a Senior Product Manager to lead our core messaging experience. You'll drive the product roadmap, work with engineering and design teams, and ensure we ship features that delight our 12M daily active users.\n\nYou'll be responsible for defining product strategy and measuring impact.`,
    requirements: `• 5+ years of product management experience\n• Experience at B2B or SaaS companies\n• Data-driven approach to product decisions\n• Strong written and verbal communication\n• Experience working with engineering teams on complex projects\n• Track record of shipping successful products`,
    applyUrl: 'https://slack.com/careers',
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Product Manager - Growth',
    company: 'Duolingo',
    location: 'Pittsburgh, PA',
    locationType: 'HYBRID',
    jobType: 'Product Manager',
    experienceLevel: 'mid',
    salaryMin: 140000,
    salaryMax: 185000,
    description: `Duolingo is the most-downloaded education app in the world. We're looking for a Growth PM to own our onboarding and retention product areas.\n\nYou'll run rigorous experiments, analyze user behavior, and ship features to our 500M+ users.`,
    requirements: `• 3+ years of product management in a consumer app\n• Experience with growth metrics and A/B testing\n• Data analysis skills with SQL\n• Strong product intuition and empathy for users\n• Ability to work in a fast-paced environment\n• Experience with mobile apps (iOS/Android) preferred`,
    applyUrl: 'https://careers.duolingo.com',
    postedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Associate Product Manager',
    company: 'Twilio',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Product Manager',
    experienceLevel: 'entry',
    salaryMin: 100000,
    salaryMax: 135000,
    description: `Twilio is looking for an Associate Product Manager to join our APM program. You'll rotate through different product areas, learning how to define and ship products for developer audiences.\n\nThis is a structured 2-year program with mentorship and career development.`,
    requirements: `• 0-2 years of experience in product, engineering, or consulting\n• Strong analytical and problem-solving skills\n• Excellent communication and collaboration\n• Technical background or interest in APIs and developer tools\n• Eagerness to learn and receive feedback\n• Bachelor's degree required`,
    applyUrl: 'https://twilio.com/company/jobs',
    postedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'VP of Product',
    company: 'Rippling',
    location: 'San Francisco, CA',
    locationType: 'ONSITE',
    jobType: 'Product Manager',
    experienceLevel: 'lead',
    salaryMin: 280000,
    salaryMax: 380000,
    description: `Rippling is building the world's first global workforce management platform. We're looking for a VP of Product to lead product strategy for our HR and IT product suite.\n\nYou'll manage a team of 15 PMs and report directly to the CEO.`,
    requirements: `• 10+ years of product management experience\n• 4+ years managing teams of PMs\n• Experience building enterprise B2B products\n• Strong executive communication and influencing skills\n• Track record of defining and executing product strategy\n• Experience in HR tech, fintech, or similar domains preferred`,
    applyUrl: 'https://rippling.com/careers',
    postedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000),
  },

  // Forward Deployment Engineers
  {
    title: 'Forward Deployment Engineer',
    company: 'Palantir',
    location: 'New York, NY',
    locationType: 'ONSITE',
    jobType: 'Forward Deployment Engineer',
    experienceLevel: 'mid',
    salaryMin: 180000,
    salaryMax: 250000,
    description: `Palantir is looking for a Forward Deployment Engineer to work directly with enterprise customers to deploy and customize our data analytics platform. You'll be embedded with clients, solving complex data problems and building custom solutions.\n\nThis role combines software engineering with customer-facing consulting.`,
    requirements: `• 3+ years of software engineering experience\n• Proficiency in Python or Java\n• Experience working with customers or stakeholders\n• Ability to understand and translate business requirements\n• Strong communication and presentation skills\n• Experience with data analysis and visualization`,
    applyUrl: 'https://palantir.com/careers',
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Forward Deployment Engineer',
    company: 'Anduril',
    location: 'Washington, DC',
    locationType: 'ONSITE',
    jobType: 'Forward Deployment Engineer',
    experienceLevel: 'senior',
    salaryMin: 200000,
    salaryMax: 280000,
    description: `Anduril Industries is a defense technology company building autonomous systems. As a Forward Deployment Engineer, you'll deploy and configure our autonomous systems software at military installations.\n\nYou'll work directly with DoD customers to understand requirements and build solutions in the field.`,
    requirements: `• 5+ years of software engineering experience\n• Ability to obtain US security clearance (US citizenship required)\n• Experience with C++ or Python in embedded/real-time systems\n• Comfort working in field or operational environments\n• Strong problem-solving skills under pressure\n• Experience with ROS, drones, or autonomous systems a plus`,
    applyUrl: 'https://anduril.com/open-roles',
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Solutions Engineer',
    company: 'Snowflake',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Forward Deployment Engineer',
    experienceLevel: 'mid',
    salaryMin: 150000,
    salaryMax: 200000,
    description: `Snowflake's solutions engineering team partners with our enterprise sales team to demonstrate the value of our data cloud platform. You'll be a technical expert helping customers understand how to migrate and scale their data workloads to Snowflake.`,
    requirements: `• 3+ years in a technical customer-facing role\n• Strong SQL and data warehousing knowledge\n• Experience with Python and data engineering\n• Excellent presentation and communication skills\n• Ability to understand customer business requirements\n• Experience with Snowflake or similar data platforms preferred`,
    applyUrl: 'https://careers.snowflake.com',
    postedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
  },

  // Designers
  {
    title: 'Senior Product Designer',
    company: 'Figma',
    location: 'San Francisco, CA',
    locationType: 'HYBRID',
    jobType: 'Designer',
    experienceLevel: 'senior',
    salaryMin: 180000,
    salaryMax: 250000,
    description: `Figma is looking for a Senior Product Designer to help design the future of design tools. Ironically, you'll be using Figma to design Figma.\n\nYou'll work on the core editing experience, collaboration features, and developer handoff.`,
    requirements: `• 5+ years of product design experience\n• Expert-level Figma skills (of course)\n• Experience designing complex, interaction-heavy interfaces\n• Strong systems thinking and ability to create design systems\n• Portfolio demonstrating product craft and attention to detail\n• Experience working closely with engineering teams`,
    applyUrl: 'https://figma.com/careers',
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'UX Designer',
    company: 'Shopify',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Designer',
    experienceLevel: 'mid',
    salaryMin: 120000,
    salaryMax: 165000,
    description: `Shopify is empowering independent businesses. We're looking for a UX Designer to help merchants create beautiful, high-converting online stores.\n\nYou'll work on our store builder, theme customization, and checkout experiences.`,
    requirements: `• 3+ years of UX or product design\n• Proficiency in Figma\n• Experience with user research and usability testing\n• Strong interaction design skills\n• Portfolio showing end-to-end design process\n• Experience with ecommerce is a plus`,
    applyUrl: 'https://shopify.com/careers',
    postedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Brand Designer',
    company: 'Stripe',
    location: 'San Francisco, CA',
    locationType: 'HYBRID',
    jobType: 'Designer',
    experienceLevel: 'mid',
    salaryMin: 130000,
    salaryMax: 175000,
    description: `Stripe's brand team creates the visual identity that's helped build one of the most recognized brands in fintech. We're looking for a Brand Designer to create campaigns, illustrations, and visual systems.\n\nYou'll work across marketing, editorial, and product surfaces.`,
    requirements: `• 3+ years of brand or graphic design\n• Expert in Figma and Adobe Creative Suite\n• Strong typography and layout skills\n• Experience with motion design is a plus\n• Portfolio demonstrating conceptual thinking and visual craft\n• Ability to work within and extend brand systems`,
    applyUrl: 'https://stripe.com/jobs',
    postedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Junior UI Designer',
    company: 'Miro',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Designer',
    experienceLevel: 'entry',
    salaryMin: 75000,
    salaryMax: 105000,
    description: `Miro, the visual collaboration platform, is looking for a Junior UI Designer. You'll be part of a team designing the whiteboard and collaboration interfaces that millions of remote teams use every day.\n\nGreat learning opportunity with access to senior designers and design system work.`,
    requirements: `• 1+ year of UI or product design experience\n• Proficiency in Figma\n• Strong visual design fundamentals\n• Understanding of interaction design principles\n• Portfolio showing UI work\n• Enthusiasm for collaboration tools`,
    applyUrl: 'https://miro.com/careers',
    postedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Design Director',
    company: 'Canva',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Designer',
    experienceLevel: 'lead',
    salaryMin: 230000,
    salaryMax: 310000,
    description: `Canva is empowering the world to design. We're looking for a Design Director to lead our core editor design team. You'll shape the vision for our flagship product used by 150 million users globally.\n\nYou'll manage a team of 12 designers and collaborate closely with Engineering and Product leadership.`,
    requirements: `• 10+ years of design experience\n• 5+ years in design leadership\n• Experience building and scaling design teams\n• Strong systems thinking and ability to define design strategy\n• Excellent communication and executive presence\n• Portfolio of shipped consumer products with measurable impact`,
    applyUrl: 'https://canva.com/careers',
    postedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000),
  },

  // Sales
  {
    title: 'Enterprise Account Executive',
    company: 'Salesforce',
    location: 'Chicago, IL',
    locationType: 'HYBRID',
    jobType: 'Sales',
    experienceLevel: 'senior',
    salaryMin: 140000,
    salaryMax: 200000,
    description: `Salesforce is looking for an Enterprise Account Executive to manage and grow relationships with Fortune 500 companies. You'll sell the full Salesforce platform — CRM, Marketing Cloud, Commerce Cloud — to enterprise customers.\n\nOTE is $280K-$400K with uncapped commission.`,
    requirements: `• 5+ years of enterprise software sales\n• Experience selling to C-suite executives\n• Track record of $1M+ quota attainment\n• Strong understanding of CRM and enterprise software\n• Excellent communication and negotiation skills\n• Experience with complex, multi-stakeholder deals`,
    applyUrl: 'https://salesforce.com/company/careers',
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Sales Development Representative',
    company: 'HubSpot',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Sales',
    experienceLevel: 'entry',
    salaryMin: 55000,
    salaryMax: 80000,
    description: `HubSpot is hiring Sales Development Representatives (SDRs) to generate pipeline for our account executive team. You'll qualify inbound leads and run outbound prospecting campaigns to SMB and mid-market companies.\n\nOTE is $75K-$100K.`,
    requirements: `• 0-2 years of sales or customer-facing experience\n• Strong written and verbal communication\n• Competitive and goal-oriented mindset\n• Familiarity with CRM tools (HubSpot or Salesforce)\n• Coachability and eagerness to learn\n• Bachelor's degree preferred but not required`,
    applyUrl: 'https://hubspot.com/jobs',
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Mid-Market Account Executive',
    company: 'Zendesk',
    location: 'San Francisco, CA',
    locationType: 'HYBRID',
    jobType: 'Sales',
    experienceLevel: 'mid',
    salaryMin: 100000,
    salaryMax: 140000,
    description: `Zendesk is looking for a Mid-Market Account Executive to drive new business in the 100-1000 employee company segment. You'll manage the full sales cycle from prospecting to close.\n\nOTE is $200K-$280K.`,
    requirements: `• 3+ years of SaaS sales experience\n• Experience selling to mid-market companies\n• Consistent quota attainment\n• Strong consultative selling skills\n• Experience with customer support or CX software a plus\n• Proficiency with Salesforce CRM`,
    applyUrl: 'https://zendesk.com/jobs',
    postedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'VP of Sales',
    company: 'Carta',
    location: 'San Francisco, CA',
    locationType: 'ONSITE',
    jobType: 'Sales',
    experienceLevel: 'lead',
    salaryMin: 250000,
    salaryMax: 350000,
    description: `Carta manages cap tables, valuations, and equity plans for 40,000 companies. We're looking for a VP of Sales to lead our GTM motion for emerging growth companies and VC firms.\n\nYou'll oversee a team of 50 sales professionals and own a $100M+ ARR target.`,
    requirements: `• 10+ years of B2B SaaS sales experience\n• 5+ years managing sales teams of 20+\n• Experience selling to CFOs, finance, and legal teams\n• Track record of scaling revenue from $50M to $200M+ ARR\n• Experience in fintech or legal tech preferred\n• Strong executive communication and board-level presence`,
    applyUrl: 'https://carta.com/careers',
    postedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
  },

  // Marketing
  {
    title: 'Product Marketing Manager',
    company: 'Twilio',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Marketing',
    experienceLevel: 'mid',
    salaryMin: 130000,
    salaryMax: 170000,
    description: `Twilio is hiring a Product Marketing Manager to lead go-to-market strategy for our Communications APIs. You'll define positioning, messaging, and launch campaigns for developer and enterprise audiences.\n\nYou'll work closely with Product, Sales, and Developer Relations.`,
    requirements: `• 3+ years of product marketing in B2B/SaaS\n• Experience marketing to developers or technical audiences\n• Strong written communication and messaging skills\n• Experience with product launches and campaigns\n• Ability to translate technical features into customer value\n• Data-driven approach to measuring marketing impact`,
    applyUrl: 'https://twilio.com/company/jobs',
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Content Marketing Manager',
    company: 'Ahrefs',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Marketing',
    experienceLevel: 'mid',
    salaryMin: 90000,
    salaryMax: 130000,
    description: `Ahrefs is one of the most popular SEO tools in the world. We're looking for a Content Marketing Manager to create in-depth educational content that helps marketers master SEO.\n\nYou'll write blog posts, produce video scripts, and build content strategy.`,
    requirements: `• 3+ years of content marketing experience\n• Deep knowledge of SEO and content strategy\n• Excellent writing and editing skills\n• Experience with Ahrefs, SEMrush, or similar tools\n• Ability to research complex topics and explain them simply\n• Experience growing organic traffic through content`,
    applyUrl: 'https://ahrefs.com/jobs',
    postedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Growth Marketing Manager',
    company: 'Canva',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Marketing',
    experienceLevel: 'senior',
    salaryMin: 140000,
    salaryMax: 190000,
    description: `Canva's growth team is responsible for driving user acquisition and activation at scale. We're looking for a Senior Growth Marketing Manager to own paid acquisition across Google, Meta, and TikTok.\n\nYou'll manage $20M+ in annual ad spend and lead a team of performance marketers.`,
    requirements: `• 5+ years of performance marketing experience\n• Experience managing $5M+ ad spend across paid channels\n• Strong analytical skills with SQL and Excel/Sheets\n• Experience with mobile app marketing and attribution\n• Knowledge of growth loops and viral mechanics\n• Experience with Looker, Amplitude, or similar analytics tools`,
    applyUrl: 'https://canva.com/careers',
    postedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Marketing Coordinator',
    company: 'Calendly',
    location: 'Atlanta, GA',
    locationType: 'HYBRID',
    jobType: 'Marketing',
    experienceLevel: 'entry',
    salaryMin: 55000,
    salaryMax: 75000,
    description: `Calendly is looking for a Marketing Coordinator to support our demand generation and field marketing teams. You'll help execute email campaigns, coordinate events, and track marketing performance.\n\nGreat entry point into SaaS marketing with opportunities to specialize.`,
    requirements: `• 0-2 years of marketing experience\n• Strong organizational and project management skills\n• Familiarity with email marketing platforms\n• Basic knowledge of marketing analytics\n• Excellent written communication\n• Bachelor's degree in marketing, communications, or related field`,
    applyUrl: 'https://calendly.com/jobs',
    postedAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Chief Marketing Officer',
    company: 'Brex',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Marketing',
    experienceLevel: 'lead',
    salaryMin: 300000,
    salaryMax: 450000,
    description: `Brex is the financial stack for modern businesses. We're looking for a CMO to define and execute our brand and demand generation strategy as we scale to $1B+ ARR.\n\nYou'll lead a team of 60 across brand, content, demand gen, and product marketing.`,
    requirements: `• 12+ years of marketing leadership experience\n• Experience scaling B2B SaaS brands from Series C to IPO stage\n• Proven track record driving pipeline and revenue growth\n• Strong executive leadership and team-building skills\n• Experience in fintech or financial services preferred\n• Ability to balance brand building with performance marketing`,
    applyUrl: 'https://brex.com/careers',
    postedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
  },

  // More jobs to reach 50+
  {
    title: 'iOS Engineer',
    company: 'DoorDash',
    location: 'San Francisco, CA',
    locationType: 'HYBRID',
    jobType: 'Frontend Engineer',
    experienceLevel: 'mid',
    salaryMin: 160000,
    salaryMax: 215000,
    description: `DoorDash is the largest food delivery platform in the US. We're looking for an iOS Engineer to work on the Dasher app used by 7 million delivery drivers.\n\nYou'll build features that help Dashers navigate deliveries, track earnings, and communicate with customers.`,
    requirements: `• 3+ years of iOS development\n• Strong Swift skills\n• Experience with UIKit and SwiftUI\n• Knowledge of performance optimization for mobile\n• Experience with MapKit or navigation APIs is a plus\n• Understanding of app analytics and crash reporting`,
    applyUrl: 'https://careers.doordash.com',
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Android Engineer',
    company: 'Cash App',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Frontend Engineer',
    experienceLevel: 'senior',
    salaryMin: 185000,
    salaryMax: 250000,
    description: `Cash App is redefining how people interact with money. We're looking for a Senior Android Engineer to build features for our 50 million user financial app.\n\nYou'll work on peer-to-peer payments, stock trading, and Bitcoin features.`,
    requirements: `• 5+ years of Android development\n• Expert Kotlin skills\n• Experience with Jetpack Compose\n• Understanding of financial security requirements\n• Experience with coroutines and flow\n• Strong testing and code quality standards`,
    applyUrl: 'https://cash.app/jobs',
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Security Engineer',
    company: 'Crowdstrike',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Backend Engineer',
    experienceLevel: 'senior',
    salaryMin: 195000,
    salaryMax: 260000,
    description: `CrowdStrike is a leader in cloud-delivered endpoint security. We're looking for a Security Engineer to work on our core detection engine that protects millions of endpoints from cyber attacks.\n\nYou'll develop detection algorithms and improve our threat intelligence systems.`,
    requirements: `• 5+ years of security engineering experience\n• Deep knowledge of Windows or Linux internals\n• Experience with malware analysis or threat intelligence\n• Strong C, C++, or Rust skills\n• Understanding of network protocols and attacks\n• Experience with threat hunting and detection engineering`,
    applyUrl: 'https://crowdstrike.com/careers',
    postedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Staff Machine Learning Engineer',
    company: 'Pinterest',
    location: 'San Francisco, CA',
    locationType: 'HYBRID',
    jobType: 'Data Scientist',
    experienceLevel: 'lead',
    salaryMin: 280000,
    salaryMax: 380000,
    description: `Pinterest is a visual discovery engine with 450M monthly active users. We're looking for a Staff ML Engineer to lead our content recommendation systems.\n\nYou'll define the technical direction for ML infrastructure powering Pinterest search and recommendations.`,
    requirements: `• 8+ years of ML engineering experience\n• Experience with large-scale recommendation systems\n• Deep Python and ML framework expertise (PyTorch, TensorFlow)\n• Experience with distributed ML training\n• Track record of leading ML platform improvements\n• Strong written and verbal communication`,
    applyUrl: 'https://pinterest.com/careers',
    postedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Technical Recruiter',
    company: 'Greenhouse',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Sales',
    experienceLevel: 'mid',
    salaryMin: 90000,
    salaryMax: 125000,
    description: `Greenhouse is the hiring platform for fast-growing companies. We're looking for a Technical Recruiter to source and recruit software engineers and data scientists.\n\nYou'll partner with hiring managers, build pipelines, and help shape our employer brand.`,
    requirements: `• 3+ years of technical recruiting experience\n• Experience recruiting software engineers and data professionals\n• Knowledge of technical skills and engineering roles\n• Strong sourcing skills (LinkedIn, GitHub, etc.)\n• Proficiency with ATS systems\n• Excellent relationship-building skills`,
    applyUrl: 'https://greenhouse.io/careers',
    postedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Infrastructure Engineer',
    company: 'GitHub',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'DevOps',
    experienceLevel: 'senior',
    salaryMin: 190000,
    salaryMax: 255000,
    description: `GitHub powers the world's software development. We're looking for an Infrastructure Engineer to help scale the systems that serve 100M+ developers.\n\nYou'll work on compute, storage, and networking infrastructure that keeps GitHub running 24/7.`,
    requirements: `• 5+ years of infrastructure or site reliability engineering\n• Experience with large-scale distributed systems\n• Strong Kubernetes and Helm expertise\n• Deep knowledge of Linux systems programming\n• Experience with Azure, AWS, or GCP\n• Experience with Terraform and infrastructure as code`,
    applyUrl: 'https://github.com/about/careers',
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'UX Researcher',
    company: 'Dropbox',
    location: 'San Francisco, CA',
    locationType: 'HYBRID',
    jobType: 'Designer',
    experienceLevel: 'mid',
    salaryMin: 130000,
    salaryMax: 170000,
    description: `Dropbox is reinventing the way people work with content. We're looking for a UX Researcher to generate insights that drive product decisions for our 700M registered users.\n\nYou'll conduct qualitative and quantitative research across web and desktop.`,
    requirements: `• 3+ years of UX research experience\n• Experience with both qualitative and quantitative methods\n• Proficiency in Figma and research tools (Maze, UserTesting)\n• Ability to translate research insights into design recommendations\n• Strong presentation and storytelling skills\n• Experience with remote user research methodologies`,
    applyUrl: 'https://dropbox.com/jobs',
    postedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Go Engineer',
    company: 'Docker',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Backend Engineer',
    experienceLevel: 'mid',
    salaryMin: 155000,
    salaryMax: 205000,
    description: `Docker is the leading container platform. We're looking for a Go Engineer to contribute to the Docker Engine and CLI — tools used by 20M+ developers worldwide.\n\nYou'll work on open source projects and ship features that improve the container development experience.`,
    requirements: `• 3+ years of Go programming experience\n• Understanding of Linux containers (namespaces, cgroups)\n• Experience with container runtimes (containerd, runc) a plus\n• Experience contributing to open source projects\n• Strong understanding of systems programming\n• Good understanding of networking and storage`,
    applyUrl: 'https://docker.com/careers',
    postedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Customer Success Manager',
    company: 'Intercom',
    location: 'Chicago, IL',
    locationType: 'HYBRID',
    jobType: 'Sales',
    experienceLevel: 'mid',
    salaryMin: 95000,
    salaryMax: 130000,
    description: `Intercom is the AI-first customer service platform. We're looking for a Customer Success Manager to help our mid-market customers get maximum value from Intercom.\n\nYou'll manage a book of business of 80 accounts and drive renewal and expansion revenue.`,
    requirements: `• 3+ years in customer success or account management\n• Experience managing B2B SaaS customer relationships\n• Strong analytical skills and ability to use product data\n• Excellent communication and presentation skills\n• Track record of achieving net revenue retention goals\n• Experience with customer support or CRM tools a plus`,
    applyUrl: 'https://intercom.com/careers',
    postedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Rust Engineer',
    company: 'Mozilla',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'Backend Engineer',
    experienceLevel: 'senior',
    salaryMin: 170000,
    salaryMax: 225000,
    description: `Mozilla is the organization behind Firefox and champions of the open web. We're looking for a Rust Engineer to work on Firefox's browser engine components.\n\nYou'll work on memory safety improvements, performance optimizations, and new web platform features.`,
    requirements: `• 5+ years of systems programming experience\n• Strong Rust expertise\n• Experience with browser internals or similar complex C++ codebases\n• Understanding of web standards and protocols\n• Experience with performance profiling and optimization\n• Passion for the open web`,
    applyUrl: 'https://mozilla.org/careers',
    postedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Product Operations Manager',
    company: 'Airtable',
    location: 'San Francisco, CA',
    locationType: 'HYBRID',
    jobType: 'Product Manager',
    experienceLevel: 'mid',
    salaryMin: 130000,
    salaryMax: 175000,
    description: `Airtable is building a no-code platform that empowers anyone to build apps. We're looking for a Product Operations Manager to bridge the gap between product teams and our customers.\n\nYou'll synthesize customer feedback, manage beta programs, and coordinate cross-team initiatives.`,
    requirements: `• 3+ years in product operations, product management, or strategy\n• Strong data analysis skills with SQL\n• Experience managing cross-functional programs\n• Excellent written and verbal communication\n• Ability to build relationships with customers and internal teams\n• Proficiency with Airtable or similar workflow tools`,
    applyUrl: 'https://airtable.com/careers',
    postedAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Site Reliability Engineer',
    company: 'PagerDuty',
    location: 'Remote',
    locationType: 'REMOTE',
    jobType: 'DevOps',
    experienceLevel: 'mid',
    salaryMin: 150000,
    salaryMax: 200000,
    description: `PagerDuty is the digital operations management platform. Fittingly, we need an SRE to ensure our own reliability. You'll work on incident response, runbooks, chaos engineering, and capacity planning.\n\nYou'll help us achieve and maintain 99.99% uptime SLAs.`,
    requirements: `• 3+ years in SRE or infrastructure engineering\n• Experience with incident management and on-call rotations\n• Strong observability skills (Prometheus, Grafana, Datadog)\n• Kubernetes and container expertise\n• Experience with chaos engineering principles\n• Good on-call discipline and incident communication skills`,
    applyUrl: 'https://pagerduty.com/careers',
    postedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000),
  },
];

async function main() {
  console.log('Seeding database...');

  // Clear existing jobs
  await prisma.job.deleteMany();

  // Create jobs
  for (const job of jobs) {
    await prisma.job.create({ data: job });
  }

  console.log(`Created ${jobs.length} jobs`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
